## Spawn two models in a subfolder

NMsim_testTwoSims <- function(path.sim,path.mod,data.sim,replace.sim=TRUE,return.text=FALSE,dir.run){
    nsims <- 2

    run.sim.0 <- fnExtension(basename(path.sim),"")
    
    if(missing(dir.run)||is.null(dir.run)) {
        dir.run <- function(file) fnExtension(path.sim,"")
    }
    folder.sim <- dir.run(path.sim)

    ## generate a skeleton - here we use the default method
    files.needed.def <- NMsim_default(path.sim=path.sim,path.mod,data.sim)

### we generate two sims
    path.sim.0 <- path.sim
    rm(path.sim)
    dt.sims <- data.table(SUBMODEL=1:nsims)
    length.num.char <- ceiling(log10(nsims))
    dt.sims[,submodel:=sprintf(fmt=paste0("%0",length.num.char,"d"),SUBMODEL)]
    dt.sims[,path.sim:=fnAppend(path.sim.0,submodel),by=.(SUBMODEL)]
    dt.sims[,fn.sim:=basename(path.sim),by=.(SUBMODEL)]
    dt.sims[,run.sim:=fnExtension(fn.sim,""),by=.(SUBMODEL)]
    dt.sims[,file.copy(path.sim.0,path.sim),by=.(SUBMODEL)]
    
### update skeleton
    ## data path is the same bcasuse they will just be copies in the same folder

    ## output tables.
#### Then, the best would be to gsub the sim name string with a
#### new subsetted simname string.

    
   sec.0 <- NMreadSection(file=path.sim.0,section="TABLE")
    dt.sims[,{
        sec.new <- gsub(run.sim.0,run.sim,x=sec.0)
        NMwriteSection(files=path.sim,section="TABLE",newlines=sec.new)
    },by=.(SUBMODEL)]
    
    
### how do we get the data moved into the subfolder? It was already saved by NMsim. Or do we not? Maybe it would be better that a simulation is always contained in its own folder. That would eliminate differences between single and multiple control stream simulations. And make it crystal clear what sims used a data file. Downside is if it's not clear what folders were generated by what commands. But can that be handled as well as in the current setup?
    
    dt.sims
}
